#!/usr/bin/env bash
case $1 in
1)
	mv zh_CN.po old_zh_CN.po
	mv en_US.po old_en_US.po
	find ./src -iname *.cpp | xargs xgettext -k_ --from-code=UTF-8 -o book-manage.pot
	msgmerge old_zh_CN.po book-manage.pot --output-file zh_CN.po
	msgmerge old_en_US.po book-manage.pot --output-file en_US.po
	rm -f old_zh_CN.po old_en_US.po book-manage.pot
	;;
2)
	mkdir -p /home/datsd/+program/book-manage/locale/en_US/LC_MESSAGES/
	mkdir -p /home/datsd/+program/book-manage/locale/zh_CN/LC_MESSAGES/
	rm -f $3/locale/zh_CN/LC_MESSAGES/*
	rm -f $3/locale/en_US/LC_MESSAGES/*
	msgfmt $3/zh_CN.po -o /tmp/$2.mo
	mv /tmp/$2.mo $3/locale/zh_CN/LC_MESSAGES/$2.mo
	msgfmt $3/en_US.po -o /tmp/$2.mo
	mv /tmp/$2.mo $3/locale/en_US/LC_MESSAGES/$2.mo
	;;
*)
	echo 未知选项
esac
